name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            output_name: timetracker.exe
            asset_name: timetracker-windows-amd64.exe
          - os: ubuntu-latest
            output_name: timetracker
            asset_name: timetracker-linux-amd64

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libgl1-mesa-dev

    - name: Run Tests (Windows)
      if: matrix.os == 'windows-latest'
      run: go test -v ./... -run '^Test[^S]' # Run all tests except screenshot tests

    - name: Run Tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: go test -v ./... # Run all tests including screenshots

    - name: Upload Screenshots as Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/initial_state.png
        if-no-files-found: error

    - name: Build
      run: go build -v -o ${{ matrix.output_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.output_name }}
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.output_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream 
